all: xing

CXX = g++

SRC = src/common.cpp \
		src/main.cpp \
		src/recommend_algorithm.cpp

LIBS = -lboost_system -lboost_thread -lglog
FLAGS = -std=c++11 -pthread -O3

xing:
	$(CXX) -o $@.bin $(SRC) $(LIBS) $(FLAGS)

clean:
	rm -rf *.bin *.bin.*
